Junit4 assignment's commit
Rishika0101/junit4-junit5-assignment pull request #1
Opened 2023-04-08 07:50 UTC by Rishika0101

Please review the code and let me know the changes that are required.

2023-04-08 07:58 UTC, anup0060 requested changes

2023-04-08 07:58 UTC, anup0060 commented on JUnit4Testing/src/main/java/org/example/StringUtils.java
> +    public static String reverse(String string) {
variable name should not be chosen as keyword name . please change

2023-04-08 07:58 UTC, anup0060 commented on JUnit4Testing/src/main/java/org/example/StringUtils.java
> +    public static boolean isEmpty(String string) {
same as above

2023-04-08 07:58 UTC, anup0060 commented on JUnit4Testing/src/main/java/org/example/StringUtils.java
> +        if(stringToCheck == "" || stringToCheck == null)
use paranthesis, even if single line add paranthesis

2023-04-08 07:58 UTC, anup0060 commented on JUnit4Testing/src/test/java/StringUtilsTest.java
> +    public void testReversee_test1()
_test1 --> wrong 

_should_reverse_given_string , we need to mention what are we testing

2023-04-11 09:53 UTC, Rishika0101 commented
As per your comment, I worked on it. Kindly check it and let me know if any mistakes are done.

2023-04-12 17:42 UTC, anup0060 requested changes

2023-04-12 17:42 UTC, anup0060 commented on JUnit4Testing_final/src/test/java/StringOperationTest.java
> +    public void testIsPalindrome_with_valid_palindrome_string() {
naming convention - testIsPalindrome_with_valid_palindrome_string  ---> 

testIsPalindrome_givenValidInput_shouldReturnWhetherPalindrome

2023-04-12 18:29 UTC, Rishika0101 commented
Worked on comments and made the changes, please review and let me know the mistakes.

2023-04-12 18:36 UTC, anup0060 approved these changes

2023-04-12 18:46 UTC, merged